name: Publish Package to npmjs
# we are lazy so we might do this later instead
# on:
#   release:
#     types: [published]

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v3 # docs https://pnpm.io/continuous-integration#github-actions
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: make install
      - run: make build
      - run: make publish 
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
